#!/bin/bash
source ~/.local/share/teleclinotify/config

if [ -z "$1" ]
then
    message="[From: $(hostname)] $(< /dev/stdin)"
else
    # exit code
    # command | tcn -e $?
    if [ "$1" = "-e" ] && [ -z "$2" ]
    then
        if [ "$2" -eq 0 ]
        then
            # success
            message="[From: $(hostname)]{success} ${@:3}"
        else
            # error
            message="[From: $(hostname)]{ERROR} ${@:3}"
        fi
    else
        message="[From: $(hostname)] $@"
    fi
fi

curl -s -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "'"$CHAT_ID"'", "text": "'"$message"'"}' \
     "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
     > /dev/null 2>/dev/null || echo "$0: http error."