#!/bin/bash
source ~/.local/share/teleclinotify/config

if [ -z "$1" ]
then
    message="[From: $(hostname)] ping"
else
    message="[From: $(hostname)] $@"
fi

curl -s -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "'"$CHAT_ID"'", "text": "'"$message"'"}' \
     "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
     > /dev/null 2>/dev/null || echo "$0: http error."